// esbuild configuration for Azure Functions
// Bundles ALL dependencies into a single self-contained file for deployment
// This is required for pnpm monorepos with workspace:* dependencies

import * as esbuild from 'esbuild';

// Build configuration - bundle EVERYTHING including @azure/functions
// Using CommonJS format because @azure/functions uses dynamic require() internally
const buildOptions = {
  entryPoints: ['./src/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs', // CommonJS format - required because @azure/functions uses require()
  outfile: './dist/index.js',
  // NOTE: We bundle ALL dependencies including @azure/functions
  // EXCEPT @azure/functions-core which is injected by the Azure Functions runtime
  // This is necessary because:
  // 1. pnpm workspace:* dependencies don't work with Azure remote builds
  // 2. @azure/functions has transitive deps (cookie, undici) that must be included
  // 3. A single self-contained bundle simplifies deployment
  external: ['@azure/functions-core'], // Only runtime-provided module stays external
  sourcemap: true,
  minify: false, // Keep readable for debugging
  treeShaking: true,
  banner: {
    js: '// Bundled Azure Functions - generated by esbuild (all deps included)',
  },
};

async function build() {
  try {
    await esbuild.build(buildOptions);
    console.log('✅ Functions bundled successfully to dist/index.js');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

build();
